---
output:
  html_document: default
  pdf_document: default
  word_document: default
---

---
title: "Statistical models for C-N cycles"
author: "Yunke Peng"
date: "June 21, 2020"
output: html_document
---

###The analysis below shows four statistical models separately

##### 1. TNPP_model - The logit function of (TNPP_1/GPP) predicted by soil C:N, age, alpha and observed fAPAR

##### 2. ANPP_model - The logit function of (ANPP_2/GPP) predicted by soil C:N, age, alpha and observed fAPAR

##### 3. NPPleaf_model - The logit function of (NPP.foliage/ANPP_2) predidicted by PPFD, Tg and vpd

##### 4. leafCN_model - The log function of leaf C/N ratio predicted by LMA and Vcmax.25

### They were all using mixed-effects model. For first three models, it considered (1|site) as the only random factor. For the last model, it considered both (1|site) and (1|species) as random factors.

### The coefficient generated in summary below will be used in next-step: global mapping of C and N cycle.

### For data sources, units, and basic information of input please refer to README.

```{r}
#Package
library(lme4)
library(nlme)
library(MuMIn)

#Input data from Euler.
CNdata <- read.csv(file="/cluster/work/climate/bestocke/data/Yunke_CNcycle/Statistical_sites/1_statistical_model.csv")
leafCN3 <- read.csv(file="/cluster/work/climate/bestocke/data/Yunke_CNcycle/Statistical_sites/2_leafCN.csv")

#remove one NA value (there is one sample when TNPP_1 > GPP)

CNdata2 <- subset(CNdata, GPP - TNPP_1 >0)

#Statistical model 1: Total NPP/GPP
TNPP_model <- lmer(log((TNPP_1/GPP)/(1-(TNPP_1/GPP)))~log(CN)+log(agee)+alpha+observedfAPAR+(1|site),data=CNdata2)

summary(TNPP_model)

r.squaredGLMM(TNPP_model)

#Statistical model 2: Aboveground NPP/GPP
ANPP_model <- lmer(log((ANPP_2/GPP)/(1-(ANPP_2/GPP)))~log(CN)+log(agee)+alpha+observedfAPAR+(1|site),data=CNdata)

summary(ANPP_model)

r.squaredGLMM(ANPP_model)

#Statistical model 3: NPP allocated to leaf/Aboveground NPP
NPPleaf_model <- lmer(log((NPP.foliage/ANPP_2)/(1-(NPP.foliage/ANPP_2)))~log(PPFD)+Tg+log(vpd)+(1|site),data=CNdata)

summary(NPPleaf_model)

r.squaredGLMM(NPPleaf_model)

#Statistical model 4: Leaf C/N 
leafCN_model <- lmer(log(cn)~log(lma)+log(Vcmax.25)+(1|final_species)+(1|sites),data=leafCN3)

summary(leafCN_model)

r.squaredGLMM(leafCN_model)

```

 