---
output:
  word_document: default
  pdf_document: default
  html_document: default
---

---
title: "Statistical models for C-N cycles"
author: "Yunke Peng"
date: "June 25, 2020"
output: html_document
---

###The analysis below shows four statistical models separately

##### 1. TNPP_model - The logit function of (TNPP_1/GPP) predicted by soil C:N, age, alpha and observed fAPAR

##### 2. ANPP_model - The logit function of (ANPP_2/GPP) predicted by soil C:N, age, alpha and observed fAPAR

##### 3. NPPleaf_model - The logit function of (NPP.foliage/ANPP_2) predidicted by PPFD, Tg and vpd

##### 4. leafCN_model - The log function of leaf C/N ratio predicted by LMA and Vcmax.25

### They were all using mixed-effects model. For first three models, it considered (1|site) as the only random factor. For the last model, it considered both (1|site) and (1|species) as random factors.

### The coefficient generated in summary below will be used in next-step: global mapping of C and N cycle.

### For data sources, units, and basic information of input please refer to README.

```{r}
#Package
library(lme4)
library(nlme)
library(MuMIn)

#Input data
CNdata <- read.csv(file= "/cluster/work/climate/bestocke/data/nimpl_sofun_inputs/sites/NPP.csv")
leafCN <- read.csv(file="/cluster/work/climate/bestocke/data/nimpl_sofun_inputs/sites/leafCN.csv")

#remove one NA value (there is one sample when TNPP_1 > GPP)

CNdata2 <- subset(CNdata, GPP - TNPP_1 >0)

#Statistical model 1: Total NPP/GPP
TNPP_model <- lmer(log((TNPP_1/GPP)/(1-(TNPP_1/GPP)))~log(CN)+log(agee)+alpha+observedfAPAR+(1|site),data=CNdata2)

summary(TNPP_model)

r.squaredGLMM(TNPP_model)

#Statistical model 2: Aboveground NPP/GPP
ANPP_model <- lmer(log((ANPP_2/GPP)/(1-(ANPP_2/GPP)))~log(CN)+log(agee)+alpha+observedfAPAR+(1|site),data=CNdata)

summary(ANPP_model)

r.squaredGLMM(ANPP_model)

#Statistical model 3: NPP allocated to leaf/Aboveground NPP
NPPleaf_model <- lmer(log((NPP.foliage/ANPP_2)/(1-(NPP.foliage/ANPP_2)))~log(PPFD)+Tg+log(vpd)+(1|site),data=CNdata)

summary(NPPleaf_model)

r.squaredGLMM(NPPleaf_model)

#Statistical model 4: Leaf C/N 

#First, we need to keep consistent for Genus speices (some data has divided Genus and species into 2 columns, while some data has include "Genus species" in 1 column) --> The consistent name was in final_species below.
for (i in 1:nrow(leafCN)){
  if (is.na(leafCN$species2[i]) == TRUE){
    leafCN$final_species[i]<- leafCN$species[i]} else { 
      leafCN$final_species[i]<- paste(leafCN$species[i],sep=" ",leafCN$species2[i])} 
}

#Second, Remove outliers
leafCN2 <- subset(leafCN,Vcmax.25>0&Vcmax.25<300&cn>1&cn<500&lma>0&lma<700)


#Third, we are interested in the site-species average data (which aggregates to one value in the same species at the same site)
Vcmax.25 <- aggregate(Vcmax.25~sites+final_species,leafCN2,mean)
cn <- aggregate(cn~sites+final_species,leafCN2,mean)
lma <- aggregate(lma~sites+final_species,leafCN2,mean)

leafCN3<-Reduce(function(x,y) merge(x = x, y = y, by = c("sites","final_species"),all.x=TRUE), 
           list(Vcmax.25,cn,lma))

leafCN_model <- lmer(log(cn)~log(lma)+log(Vcmax.25)+(1|final_species)+(1|sites),data=leafCN3)

summary(leafCN_model)

r.squaredGLMM(leafCN_model)

```

